# -*- coding: utf-8 -*-
"""EMSCodeLLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3Ru7Ut6a6klrOh4_e6LioKKjtknGPTT

# EMS Protocol LLM: T5-base

## 0 · Installations
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install transformers>=4.40.0 torch datasets rouge-score nltk sentencepiece
# 
# import torch
# import nltk
# nltk.download('punkt',     quiet=True)
# nltk.download('punkt_tab', quiet=True)
# 
# print('CUDA:', torch.cuda.is_available())
# if torch.cuda.is_available():
#     print('GPU:', torch.cuda.get_device_name(0))
#     print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

"""## 1 · Imports"""

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import re
import nltk
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from torch.optim import AdamW
from transformers import T5ForConditionalGeneration, T5Tokenizer, get_cosine_schedule_with_warmup
from sklearn.model_selection import train_test_split
from rouge_score import rouge_scorer
from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction

warnings.filterwarnings('ignore')
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {DEVICE}')

"""## 2 · Config"""

CONFIG = {
    'model_name':'t5-base',
    'prefix': 'ems protocol: ',
    'max_input_len': 256,
    'max_target_len': 300,
    'batch_size': 16,
    'epochs': 15,
    'learning_rate': 1e-4,
    'warmup_ratio': 0.05,
    'weight_decay': 0.01,
    'patience': 3,
    'grad_clip': 1.0,
    'data_path': 'ems_scenarios_5000.csv',
    'test_size': 0.10,
    'val_size': 0.10,
    'seed': 42,
    'output_dir': './ems_t5base_output',
}

torch.manual_seed(CONFIG['seed'])
np.random.seed(CONFIG['seed'])
os.makedirs(CONFIG['output_dir'], exist_ok=True)
print('Config set.')
print(f'Model: {CONFIG["model_name"]}')
print(f'Batch size: {CONFIG["batch_size"]}')
print(f'Max epochs: {CONFIG["epochs"]} (early stopping patience={CONFIG["patience"]})')

"""## 3 · Data Loading + Class Balance"""

CATEGORY_KEYWORDS = {
    'cardiac':     ['chest pain','cardiac','heart','MI','STEMI','AED','CPR','arrest','arrhythmia'],
    'respiratory': ['respiratory','breathing','asthma','COPD','dyspnea','SpO2','wheez','bronch'],
    'stroke':      ['stroke','CVA','facial droop','FAST','hemiplegia','aphasia'],
    'trauma':      ['trauma','fracture','laceration','hemorrhage','bleeding','MVC','fall','burn','crush'],
    'diabetic':    ['diabetic','hypoglycemia','glucose','dextrose','glucagon','DKA'],
    'anaphylaxis': ['anaphylaxis','allergic','epinephrine','epipen','angioedema','hives'],
    'overdose':    ['overdose','opioid','naloxone','narcan','poisoning','ingestion','toxin'],
    'pediatric':   ['child','infant','pediatric','neonate','toddler','juvenile'],
    'obstetric':   ['pregnant','labor','delivery','eclampsia','preeclampsia'],
    'seizure':     ['seizure','convuls','epilep','postictal','status epilepticus'],
}

def tag_category(text):
    tl = text.lower()
    for cat, kws in CATEGORY_KEYWORDS.items():
        if any(k.lower() in tl for k in kws):
            return cat
    return 'other'

def clean(t):
    t = re.sub(r'\s+', ' ', t)
    t = re.sub(r'\.{2,}', '.', t)
    return t.strip()

df = pd.read_csv(CONFIG['data_path'])
df['scenario'] = df['scenario'].apply(clean)
df['response']  = df['response'].apply(clean)
df = df[
    (df.scenario.str.len() > 20) &
    (df.response.str.len()  > 20)
].drop_duplicates('scenario').reset_index(drop=True)
df['category'] = df['scenario'].apply(tag_category)

print(f'Total usable rows: {len(df)}')
print(f'Avg scenario words: {df.scenario.str.split().str.len().mean():.0f}')
print(f'Avg response words: {df.response.str.split().str.len().mean():.0f}')
print(f'\nCategory distribution:')
print(df.category.value_counts())

train_df, temp = train_test_split(df, test_size=CONFIG['test_size']+CONFIG['val_size'], stratify=df['category'], random_state=CONFIG['seed'])
val_df,  test_df = train_test_split(temp, test_size=0.5, stratify=temp['category'], random_state=CONFIG['seed'])
train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

print(f'\nSplit: Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}')

cat_counts       = train_df['category'].value_counts().to_dict()
sample_weights   = train_df['category'].map(lambda c: 1.0 / cat_counts[c]).tolist()
weighted_sampler = WeightedRandomSampler(sample_weights, len(sample_weights), replacement=True)
print('Ready: all categories train equally')

"""## 4 · Dataset + DataLoaders"""

class EMSDataset(Dataset):
    def __init__(self, df, tokenizer):
        self.scenarios = df['scenario'].tolist()
        self.responses  = df['response'].tolist()
        self.tokenizer  = tokenizer

    def __len__(self):
        return len(self.scenarios)

    def __getitem__(self, idx):
        input_text  = CONFIG['prefix'] + self.scenarios[idx]
        target_text = self.responses[idx]

        input_enc = self.tokenizer(
            input_text,
            max_length=CONFIG['max_input_len'],
            padding='max_length',
            truncation=True,
            return_tensors='pt',
        )
        target_enc = self.tokenizer(
            target_text,
            max_length=CONFIG['max_target_len'],
            padding='max_length',
            truncation=True,
            return_tensors='pt',
        )

        labels = target_enc['input_ids'].squeeze()
        labels[labels == self.tokenizer.pad_token_id] = -100  # ignore padding in loss

        return {
            'input_ids':      input_enc['input_ids'].squeeze(),
            'attention_mask': input_enc['attention_mask'].squeeze(),
            'labels':         labels,
        }

# Load tokenizer
print(f'Loading {CONFIG["model_name"]} tokenizer...')
tokenizer = T5Tokenizer.from_pretrained(CONFIG['model_name'])

train_dataset = EMSDataset(train_df, tokenizer)
val_dataset = EMSDataset(val_df,   tokenizer)
test_dataset = EMSDataset(test_df,  tokenizer)

train_loader = DataLoader(
    train_dataset,
    batch_size=CONFIG['batch_size'],
    sampler=weighted_sampler,
    num_workers=4,
    pin_memory=True,
)
val_loader = DataLoader(
    val_dataset,
    batch_size=CONFIG['batch_size'],
    shuffle=False,
    num_workers=4,
    pin_memory=True,
)

print(f'Train batches: {len(train_loader)} | Val batches: {len(val_loader)}')

"""## 5 · Load Model"""

print(f'Loading {CONFIG["model_name"]} model...')
model = T5ForConditionalGeneration.from_pretrained(CONFIG['model_name']).to(DEVICE)
total = sum(p.numel() for p in model.parameters())
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'Total params:     {total:,}')
print(f'Trainable params: {trainable:,}')
scaler = None
optimizer = AdamW(model.parameters(), lr=CONFIG['learning_rate'], weight_decay=CONFIG['weight_decay'])
total_steps = len(train_loader) * CONFIG['epochs']
warmup_steps = int(total_steps * CONFIG['warmup_ratio'])
scheduler = get_cosine_schedule_with_warmup(optimizer, warmup_steps, total_steps)

print(f'LR: {CONFIG["learning_rate"]}')
print(f'Total steps: {total_steps} | Warmup: {warmup_steps}')

"""## 6 · Training Loop"""

def train_epoch(model, loader, optimizer, scheduler, scaler):
    model.train()
    total_loss = 0.0
    for batch in loader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(DEVICE)
        attention_mask = batch['attention_mask'].to(DEVICE)
        labels = batch['labels'].to(DEVICE)
        if scaler:
            with torch.cuda.amp.autocast():
                loss = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels).loss
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), CONFIG['grad_clip'])
            scaler.step(optimizer)
            scaler.update()
        else:
            loss = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels).loss
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), CONFIG['grad_clip'])
            optimizer.step()
        scheduler.step()
        total_loss = total_loss + loss.item()
    return total_loss / len(loader)

def eval_loss(model, loader):
    model.eval()
    total_loss = 0.0
    with torch.no_grad():
        for batch in loader:
            loss = model(
                input_ids=batch['input_ids'].to(DEVICE),
                attention_mask=batch['attention_mask'].to(DEVICE),
                labels=batch['labels'].to(DEVICE),
            ).loss
            total_loss = total_loss + loss.item()
    return total_loss / len(loader)

#main training
best_val_loss  = float('inf')
patience_count = 0
train_losses, val_losses = [], []
best_model_path = os.path.join(CONFIG['output_dir'], 'best_model')

print(f'Training {CONFIG["model_name"]} for up to {CONFIG["epochs"]} epochs...\n')

for epoch in range(1, CONFIG['epochs'] + 1):
    tr_loss = train_epoch(model, train_loader, optimizer, scheduler, scaler)
    vl_loss = eval_loss(model, val_loader)
    train_losses.append(tr_loss)
    val_losses.append(vl_loss)

    improved = vl_loss < best_val_loss
    if improved:
        best_val_loss = vl_loss
        patience_count = 0
        model.save_pretrained(best_model_path)
        tokenizer.save_pretrained(best_model_path)
        marker = 'saved'
    else:
        patience_count += 1
        marker = f'patience {patience_count}/{CONFIG["patience"]}'

    print(f'Epoch {epoch:02d}/{CONFIG["epochs"]}  '
          f'Train: {tr_loss:.4f}  Val: {vl_loss:.4f}  [{marker}]')

    if patience_count >= CONFIG['patience']:
        print(f'\nEarly stopping at epoch {epoch}.')
        break

print(f'\nBest val loss: {best_val_loss:.4f}')
print(f'Best model saved to {best_model_path}')

"""## 7 · Training Curve Plot"""

fig, ax = plt.subplots(figsize=(10, 4))
epochs = range(1, len(train_losses) + 1)
ax.plot(epochs, train_losses, 'b-o', label='Train Loss', linewidth=2)
ax.plot(epochs, val_losses,   'r-o', label='Val Loss',   linewidth=2)
ax.axvline(x=val_losses.index(min(val_losses))+1, color='green', linestyle='--', alpha=0.7, label='Best checkpoint')
ax.set_xlabel('Epoch')
ax.set_ylabel('Loss')
ax.set_title(f'EMS T5-base — Training Curves')
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(CONFIG['output_dir'], 'training_curves.png'), dpi=150)
plt.show()
print('Saved training_curves.png')

"""## 8 · Load Best Model + Generate"""

print('Loading best checkpoint...')
best_model = T5ForConditionalGeneration.from_pretrained(best_model_path).to(DEVICE)
best_model.eval()

def generate_response(scenario: str, max_len: int = 300) -> str:
    input_text = CONFIG['prefix'] + scenario
    inputs = tokenizer(
        input_text,
        return_tensors='pt',
        max_length=CONFIG['max_input_len'],
        truncation=True,
    ).to(DEVICE)
    with torch.no_grad():
        out = best_model.generate(
            inputs['input_ids'],
            attention_mask=inputs['attention_mask'],
            max_length=max_len,
            num_beams=4,
            early_stopping=True,
            no_repeat_ngram_size=3,
            length_penalty=1.2,
        )
    return tokenizer.decode(out[0], skip_special_tokens=True)

sample = test_df.iloc[0]['scenario']
print(f'\nSample scenario: {sample[:100]}...')
print(f'Generated: {generate_response(sample)[:200]}...')

"""## 9 · Full Evaluation — ROUGE + BLEU"""

scorer_rouge = rouge_scorer.RougeScorer(['rouge1','rouge2','rougeL'], use_stemmer=True)
r1, r2, rL   = [], [], []
hypotheses, references_tok = [], []

print(f'Evaluating on {len(test_df)} test samples...')
sc_test = test_df['scenario'].tolist()
re_test = test_df['response'].tolist()

predictions = []
for i, (sc, ref) in enumerate(zip(sc_test, re_test)):
    pred = generate_response(sc)
    predictions.append(pred)

    s = scorer_rouge.score(ref, pred)
    r1.append(s['rouge1'].fmeasure)
    r2.append(s['rouge2'].fmeasure)
    rL.append(s['rougeL'].fmeasure)

    hypotheses.append(nltk.word_tokenize(pred.lower()))
    references_tok.append([nltk.word_tokenize(ref.lower())])

    if (i + 1) % 50 == 0:
        print(f'  {i+1}/{len(sc_test)} — ROUGE-1: {np.mean(r1):.4f}')

bleu = corpus_bleu(references_tok, hypotheses, smoothing_function=SmoothingFunction().method1)

test_metrics = {
    'ROUGE-1': np.mean(r1),
    'ROUGE-2': np.mean(r2),
    'ROUGE-L': np.mean(rL),
    'BLEU':    bleu,
}

print(f'Test Set Evaluation — {CONFIG["model_name"]}')
for name, val in test_metrics.items():
    bar = '█' * int(val * 40)
    print(f'  {name:<10} {val:.4f}  {bar}')
print(f'{"="*50}')

# Interpretation
r1_val = test_metrics['ROUGE-1']
print('\nInterpretation:')
if r1_val >= 0.55:   print('  ROUGE-1: EXCELLENT — model captures protocol content very well')
elif r1_val >= 0.40: print('  ROUGE-1: GOOD — model captures most key protocol terms')
elif r1_val >= 0.25: print('  ROUGE-1: FAIR — partial match; consider more epochs')
else:                print('  ROUGE-1: POOR — model needs more training data or epochs')

# Save metrics
with open(os.path.join(CONFIG['output_dir'], 'test_metrics.txt'), 'w') as f:
    f.write(f'EMS T5-base Test Metrics\n{"="*40}\n')
    for k, v in test_metrics.items():
        f.write(f'{k}: {v:.4f}\n')
    f.write(f'\nBest val loss: {best_val_loss:.4f}\n')
    f.write(f'Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}\n')
print('Metrics saved.')

"""## 10 · Metrics Bar Chart"""

fig, ax = plt.subplots(figsize=(8, 4))
colors  = ['#1d3557','#1d3557','#1d3557','#e63946']
bars    = ax.bar(test_metrics.keys(), test_metrics.values(), color=colors, width=0.5)
ax.set_ylim(0, 1.0)
ax.set_ylabel('Score')
ax.set_title(f'EMS {CONFIG["model_name"]} — Test Set Metrics')
for bar, val in zip(bars, test_metrics.values()):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
            f'{val:.3f}', ha='center', fontsize=12, fontweight='bold')
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(CONFIG['output_dir'], 'metrics_bar.png'), dpi=150)
plt.show()

"""## 11 · ROUGE-1 by Emergency Category"""

cat_results = []
for sc, ref, pred in zip(sc_test, re_test, predictions):
    cat = tag_category(sc)
    r1_score = scorer_rouge.score(ref, pred)['rouge1'].fmeasure
    cat_results.append({'category': cat, 'rouge1': r1_score})

df_cat = pd.DataFrame(cat_results)
cat_scores = df_cat.groupby('category')['rouge1'].agg(['mean','count']).sort_values('mean', ascending=False)
print(cat_scores)

fig, ax = plt.subplots(figsize=(10, 4))
cat_scores['mean'].plot(kind='bar', ax=ax, color='#1d3557', width=0.6)
ax.set_ylabel('ROUGE-1 Score')
ax.set_title('ROUGE-1 by Emergency Category')
ax.set_xticklabels(cat_scores.index, rotation=30, ha='right')
ax.set_ylim(0, 1.0)
for i, (_, row) in enumerate(cat_scores.iterrows()):
    ax.text(i, row['mean'] + 0.02, f"{row['mean']:.2f}\n(n={int(row['count'])})",
            ha='center', fontsize=8, fontweight='bold')
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(CONFIG['output_dir'], 'rouge_by_category.png'), dpi=150)
plt.show()

"""## 12 · Best / Median / Worst Predictions"""

scored = sorted( zip(r1, sc_test, re_test, predictions), key=lambda x: x[0])

examples = [
    ('BEST',   scored[-1]),
    ('MEDIAN', scored[len(scored)//2]),
    ('WORST',  scored[0]),
]

for label, (score, sc, ref, pred) in examples:
    print(f'\n── {label}  (ROUGE-1: {score:.3f}) ' + '─'*40)
    print(f'SCENARIO : {sc[:150]}...')
    print(f'REFERENCE: {ref[:200]}...')
    print(f'GENERATED: {pred[:200]}...')

"""## 13 · Test on Your Own Scenarios"""

CATEGORY_LABELS = [
    'Cardiac Arrest',
    'Stroke',
    'Pediatric Respiratory',
    'Diabetic Emergency',
    'Trauma / Hemorrhage',
]

TEST_SCENARIOS = [
    '62-year-old male found unresponsive in his driveway. Bystander CPR in progress. No pulse, no respirations. AED on scene shows shockable rhythm. Last seen normal 8 minutes ago.',
    '71-year-old female with sudden onset right-sided facial droop, arm weakness and slurred speech. Symptoms started 45 minutes ago. Blood pressure 188/102, GCS 13.',
    '7-year-old male with known asthma, severe wheezing, accessory muscle use, SpO2 88%. Albuterol given 20 minutes ago with no improvement.',
    '55-year-old female found confused and diaphoretic at her desk. Blood glucose 28 mg/dL. Conscious but unable to follow commands.',
    '34-year-old male, high-speed motorcycle collision. GCS 8, femur fracture with active bleeding. BP 88/60, HR 124.',
]

print()
print('  EMS PROTOCOL GENERATOR — Test Scenario Results')
print('  Model: T5-base  |  Fine-tuned on NEMSIS 2024')
print()

for i, (scenario, label) in enumerate(zip(TEST_SCENARIOS, CATEGORY_LABELS)):
    response = generate_response(scenario)

    print(f'  [{i+1}/5]  {label}')
    print()

    print('  SCENARIO')
    words = scenario.split()
    line = '    '
    for word in words:
        if len(line) + len(word) > 72:
            print(line)
            line = '    ' + word + ' '
        else:
            line += word + ' '
    print(line)
    print()

    print('  PROTOCOL RESPONSE')
    words = response.split()
    line = '    '
    for word in words:
        if len(line) + len(word) > 72:
            print(line)
            line = '    ' + word + ' '
        else:
            line += word + ' '
    print(line)
    print()
    print('  ' + '-'*66)
    print()

print(f'  {len(TEST_SCENARIOS)} scenarios completed.')
print()

"""## 14 · Interactive Widget"""

import ipywidgets as widgets
from IPython.display import display, Javascript

display(widgets.HTML("""
<style>
  .ems-title {
    font-family: 'IBM Plex Sans', system-ui, sans-serif;
    font-size: 20px;
    font-weight: 600;
    color: #0d2137;
    margin: 16px 0 4px;
    letter-spacing: -0.01em;
  }
  .ems-subtitle {
    font-family: system-ui, sans-serif;
    font-size: 12px;
    color: #5a7085;
    margin-bottom: 20px;
    letter-spacing: 0.04em;
    text-transform: uppercase;
  }
  .ems-label {
    font-family: system-ui, sans-serif;
    font-size: 11px;
    font-weight: 600;
    color: #5a7085;
    text-transform: uppercase;
    letter-spacing: 0.07em;
    margin-bottom: 6px;
  }
  .ems-divider {
    border: none;
    border-top: 1px solid #d0dae6;
    margin: 20px 0;
  }
  .ems-generate-btn button {
    color: white !important;
    font-weight: 500 !important;
  }
</style>

<div class="ems-title">EMS Protocol LLM</div>
"""))

display(widgets.HTML('<div class="ems-label">Emergency Scenario</div>'))

scenario_box = widgets.Textarea(
    placeholder='Describe the emergency - patient age, chief complaint, vitals, context...',
    layout=widgets.Layout(width='100%', height='110px'),
    style={'font_size': '14px'}
)
display(scenario_box)

btn = widgets.Button(
    description='Generate Protocol',
    layout=widgets.Layout(height='36px', width='180px'),
    style={'button_color': 'red', 'font_weight': '500'}
)
btn.add_class('ems-generate-btn')

status = widgets.HTML(value='', layout=widgets.Layout(margin='0 0 0 12px'))

display(widgets.HBox(
    [btn, status],
    layout=widgets.Layout(align_items='center', margin='10px 0 0 0')
))

display(widgets.HTML('<hr class="ems-divider"><div id="ems-output-anchor"></div><div class="ems-label">Generated Protocol Response</div>'))

output_box = widgets.Textarea(
    placeholder='Protocol response will appear here...',
    layout=widgets.Layout(width='100%', height='220px'),
    disabled=True,
    style={'font_size': '13px', 'font_family': 'monospace', 'background': '#f4f7fa'}
)
display(output_box)

def on_click(b):
    scenario = scenario_box.value.strip()
    if not scenario:
        status.value = '<span style="color:#c0392b; font-size:12px;">⚠ Please enter a scenario.</span>'
        return
    btn.disabled = True
    status.value = '<span style="color:#5a7085; font-size:12px; font-style:italic;">Generating...</span>'
    output_box.value = generate_response(scenario)
    status.value = '<span style="color:#1a6640; font-size:12px;">✓ Done.</span>'
    btn.disabled = False
    display(Javascript("""
        document.getElementById('ems-output-anchor').scrollIntoView({
            behavior: 'smooth', block: 'start'
        });
    """))

btn.on_click(on_click)